language: python
sudo: required
dist: trusty
cache: pip
python:
  - "pypy2.7"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    include:
      - python: 'pypy2.7'
        env: TOXENV='pypy-dj1.7,pypy-dj1.8,pypy-dj1.9,pypy-dj1.10'
      - python: '2.7'
        env: TOXENV='py2.7-dj1.7,py2.7-dj1.8,py2.7-dj1.9,py2.7-dj1.10'
      - python: '3.3'
        env: TOXENV='py3.3-cov,py3.3-dj1.7,py3.3-dj1.8,py3.3-dj1.9,py3.3-dj1.10'
      - python: '3.4'
        env: TOXENV='py3.4-dj1.7,py3.4-dj1.8,py3.4-dj1.9,py3.4-dj1.10,py3.4-dj1.11'
      - python: '3.5'
        env: TOXENV='py3.5-dj1.8,py3.5-dj1.9,py3.5-dj1.10,py3.5-dj1.11,py3.5-dj2.0'
      - python: '3.6'
        env: TOXENV='cov,py3.6-dj1.8,py3.6-dj1.9,py3.6-dj1.10,py3.6-dj1.11,py3.6-dj2.0'
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls