language: python
sudo: false
python:
  - "pypy2.7"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=py2.7-dj1.7
    - TOXENV=py2.7-dj1.8
    - TOXENV=py2.7-dj1.9
    - TOXENV=py2.7-dj1.10
    - TOXENV=py3.3-dj1.7
    - TOXENV=py3.3-dj1.8
    - TOXENV=py3.4-dj1.7
    - TOXENV=py3.4-dj1.8
    - TOXENV=py3.4-dj1.9
    - TOXENV=py3.4-dj1.10
    - TOXENV=py3.5-dj1.8
    - TOXENV=py3.5-dj1.9    
    - TOXENV=py3.5-dj1.10
    - TOXENV=py3.5-dj1.11
    - TOXENV=py3.5-dj2.0
    - TOXENV=py3.6-dj1.8
    - TOXENV=py3.6-dj1.9
    - TOXENV=py3.6-dj1.10
    - TOXENV=py3.6-dj1.11
    - TOXENV=py3.6-dj2.0
    - TOXENV=pypy-dj1.7
    - TOXENV=pypy-dj1.8
    - TOXENV=pypy-dj1.9
    - TOXENV=pypy-dj1.10
    - TOXENV=cov
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls