language: python
sudo: false
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=py27-dj1.7
    - TOXENV=py27-dj1.8
    - TOXENV=py27-dj1.9
    - TOXENV=py27-dj1.10
    - TOXENV=py27-dj1.11
    - TOXENV=py34-dj1.7
    - TOXENV=py34-dj1.8
    - TOXENV=py34-dj1.9
    - TOXENV=py34-dj1.10
    - TOXENV=py34-dj1.11
    - TOXENV=py35-dj1.8
    - TOXENV=py35-dj1.9
    - TOXENV=py35-dj1.10
    - TOXENV=py35-dj1.11
    - TOXENV=py35-dj2.0
    - TOXENV=py36-dj1.8
    - TOXENV=py36-dj1.9
    - TOXENV=py36-dj1.10
    - TOXENV=py36-dj1.11
    - TOXENV=py36-dj2.0
    - TOXENV=cov
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls