language: python
sudo: false
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: TOXENV=cov }
    - { python: "3.6", env: TOXENV=py3.6-dj1.8 }
    - { python: "3.6", env: TOXENV=py3.6-dj1.9 }
    - { python: "3.6", env: TOXENV=py3.6-dj1.10 }
    - { python: "3.6", env: TOXENV=py3.6-dj1.11 }
    - { python: "3.6", env: TOXENV=py3.6-dj2.0 }
    - { python: "3.5", env: TOXENV=py3.5-dj1.8 }
    - { python: "3.5", env: TOXENV=py3.5-dj1.9 }
    - { python: "3.5", env: TOXENV=py3.5-dj1.10 }
    - { python: "3.5", env: TOXENV=py3.5-dj1.11 }
    - { python: "3.5", env: TOXENV=py3.5-dj2.0 }
    - { python: "3.4", env: TOXENV=py3.4-dj1.8 }
    - { python: "3.4", env: TOXENV=py3.4-dj1.9 }
    - { python: "3.4", env: TOXENV=py3.4-dj1.10 }
    - { python: "3.4", env: TOXENV=py3.4-dj1.11 }
    - { python: "3.3", env: TOXENV=py3.3-dj1.7 }
    - { python: "3.3", env: TOXENV=py3.3-dj1.8 }
    - { python: "3.3", env: TOXENV=py3.3-dj1.9 }
    - { python: "3.3", env: TOXENV=py3.3-dj1.10 }
    - { python: "2.7", env: TOXENV=py2.7-dj1.7 }
    - { python: "2.7", env: TOXENV=py2.7-dj1.8 }
    - { python: "2.7", env: TOXENV=py2.7-dj1.9 }
    - { python: "2.7", env: TOXENV=py2.7-dj1.10 }
    - { python: "pypy2.7", env: TOXENV=pypy-dj1.7 }
    - { python: "pypy2.7", env: TOXENV=pypy-dj1.8 }
    - { python: "pypy2.7", env: TOXENV=pypy-dj1.9 }
    - { python: "pypy2.7", env: TOXENV=pypy-dj1.10 }
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls