language: python
sudo: required
dist: trusty
cache: pip
python:
  - "pypy2.7"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    include:
      - python: 'pypy2.7'
        env: TOXENV='cov,dj1.7,dj1.8,dj1.9,dj1.10'
      - python: '2.7'
        env: TOXENV='cov,dj1.7,dj1.8,dj1.9,dj1.10'
      - python: '3.3'
        env: TOXENV='cov,dj1.7,dj1.8,dj1.9,dj1.10'
      - python: '3.4'
        env: TOXENV='cov,dj1.7,dj1.8,dj1.9,dj1.10,dj1.11'
      - python: '3.5'
        env: TOXENV='cov,dj1.8,dj1.9,dj1.10,dj1.11,dj2.0'
      - python: '3.6'
        env: TOXENV='cov,dj1.8,dj1.9,dj1.10,dj1.11,dj2.0'
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls